---
- name: Search for new users
  shell: grep "^{{item.username}}:!:" /etc/shadow | sed "s/:.*//"
  with_items: users
  changed_when: false
  register: new_users

- name: Force password change on next login
  shell: usermod -p "" {{item}} && chage -d 0 {{item}}
  with_items: new_users.stdout_lines
