---
galaxy_info:
  author: Sergey Korolev
  description: Simple /etc/sudoers.d management role
  license: MIT
  min_ansible_version: 1.3
  platforms:
  - name: EL
    versions:
    - all
  - name: Fedora
    versions:
    - all
  - name: opensuse
    versions:
    - all
  - name: Ubuntu
    versions:
    - all
  - name: SLES
    versions:
    - all
  - name: GenericLinux
    versions:
    - all
    - any
  - name: Debian
    versions:
    - all
  categories:
  - system
dependencies: []