# Install Cisco AnyConnect VPN client
---
# Just add these aliases to .zshrc and let the user take care of the installation / execution

- name: Install dependencies for Cisco AnyConnect VPN client
  apt: name={{ item }}
  with_items:
    - screen
    - libatk1.0-0
    - libgtk2.0-0
    - libpangox-1.0-0
    - libpangoxft-1.0-0

- lineinfile: >
    dest=/home/vagrant/.zshrc
    line="{{ item }}"
  with_items:
    - "{{ '#' }} Aliases for Cisco Anyconnect VPN client"
    - alias vpn-install='find /vagrant/roles/anyconnect/files/anyconnect-linux64-*.sh | sort | tail -n 1 | xargs sudo && for FILE in /etc/ssl/certs/*; do sudo ln -s $FILE /opt/.cisco/certificates/ca/$(basename $FILE); done'
    #- alias vpn-connect='sudo /opt/cisco/anyconnect/bin/vpn connect YOURSERVER && sudo iptables -I ciscovpn -s 192.168.121.1 -j ACCEPT'
    - alias vpn-connect='sudo /opt/cisco/anyconnect/bin/vpn connect YOURSERVER'
    - alias vpn-disconnect='sudo /opt/cisco/anyconnect/bin/vpn disconnect'
