# Install Cisco AnyConnect VPN client
---
# Just add these aliases to .zshrc and let the user take care of the installation / execution

- name: Install dependencies for Cisco AnyConnect VPN client
  apt: name={{ item }}
  with_items:
    - screen
    - libatk1.0-0
    - libgtk2.0-0
    - libpangox-1.0-0
    - libpangoxft-1.0-0

- name: Install helper scripts for Cisco AnyConnect VPN client
  template: src="{{ item }}.j2" dest="/usr/local/bin//{{ item }}" mode=0755
  with_items:
    - vpn-connect
    - vpn-disconnect
    - vpn-install
